version: '3.3'

services:
  manager1:
    image: docker:stable-dind
    hostname: manager1
    privileged: true
    volumes:
      - manager1:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:
        ipv4_address: 172.16.238.201
  manager2:
    image: docker:stable-dind
    hostname: manager2
    privileged: true
    volumes:
      - manager2:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:
        ipv4_address: 172.16.238.202
  manager3:
    image: docker:stable-dind
    hostname: manager3
    privileged: true
    volumes:
      - manager3:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:
        ipv4_address: 172.16.238.203
  worker1:
    image: docker:stable-dind
    hostname: worker1
    privileged: true
    volumes:
      - worker1:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:
  worker2:
    image: docker:stable-dind
    hostname: worker2
    privileged: true
    volumes:
      - worker2:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:
  worker3:
    image: docker:stable-dind
    hostname: worker3
    privileged: true
    volumes:
      - worker3:/var/lib/docker
    command: --storage-driver=overlay2
    networks:
      swarm:

volumes:
  manager1:
  manager2:
  manager3:
  worker1:
  worker2:
  worker3:

networks:
  swarm:
    ipam:
      config:
        - subnet: 172.16.238.0/24
